on:
  push:
    branches:
      - main
  workflow_dispatch:
    # paths: ['**.Rmd']

name: Render and Publish Website

permissions:
  contents: write
  pages: write

jobs:
  render-website:
    runs-on: macos-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          #token: ${{ secrets.GH_ACTION }}

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          extra-repositories: 'https://stan-dev.r-universe.dev https://andrjohns.r-universe.dev'

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::rmarkdown
            any::cmdstanr
            any::StanEstimators
            any::randcorr
            any::sn

      - name: Cache CmdStan
        id: cache-cmdstan
        uses: actions/cache@v4
        with:
          path: ~/.cmdstan
          key: gha-cmdstan

      - name: Setup cmdstan
        if: steps.cache-cmdstan.outputs.cache-hit != 'true'
        run: cmdstanr::install_cmdstan(cores = 2)
        shell: Rscript {0}

      - name: Render and Publish Website
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
